### ISSUE TITLE
Try the caffe Windows port 

### ISSUE THREAD

**Issue by pkrush** [GemHunt/CoinSorter#19]
Try a caffe Windows port and add a script and maybe binaries for this usage. 

Even if it's just for classifying with no GPU it would really handy. 

I can see there is a culture pushing against using a caffe Windows port, admirable yes, but in practice for this project it's a bit silly. 

The open caffe issue for this is handy:
https://github.com/BVLC/caffe/issues/15

The Unofficial 64-bit Windows port is:
https://github.com/niuzhiheng/caffe

Since VS 2013 is free this might be a great resource:
https://initialneil.wordpress.com/2015/01/11/build-caffe-in-windows-with-visual-studio-2013-cuda-6-5-opencv-2-4-9/

Another VS 2013 port page:
http://mthust.github.io/2015/04/Build-Caffe-with-Visual-Studio-2013-on-Windows-7-x64-using-Cuda-7.0/

**Comment by lunzueta** [comment]
@pkrush, you should check the most updated Windows port of Caffe, which is that of @willyd as mentioned in Caffe's Wiki (https://github.com/BVLC/caffe/wiki/Installation), but not yet in Caffe's website (which can be quite confusing). You'll see that its structure is pretty much the same as that of Linux/OSX (it's quite close from its latest state). As mentioned in Caffe's Wiki, this version also has a cmake-based super builder, which downloads, compiles and links all the required dependencies and solves all those Linux/OSX-to-Windows compatibility issues (such as the inclusion of unistd.h, etc). You just need to use CMake and Visual Studio (in my case I used CMake 3.3.0 and VS2013, and did a 64-bit build, and it worked perfectly). Just for curiosity, I've also tested the super builder with VS2015 and I got some errors that I didn't get with VS2013, so I guess, for now VS2013 should be used.

**Comment by pkrush** [comment]
Thanks for the comments, I will look into @willyd ’s work. 

It’s interesting your trying to bring DIGITS to Windows as well. 

Also, thanks for the being the first person to contribute to this repo!

**Comment by lunzueta** [comment]
Thanks @pkrush. You can follow up what's being done around Caffe to make Digits work in Windows here: https://github.com/willyd/caffe-builder/issues/6
