### ISSUE TITLE
Image dataset 404?

### ISSUE THREAD

**Issue by chmullig** [GemHunt/CoinSorter#68]
Thanks for posting this intriguing project! I'd love to check it out. One thing though, on  https://github.com/GemHunt/sail you link to a dataset of images http://www.gemhunt.com/cents.tar.gz which doesn't exist. Would it be possible to post an updated link? Does that file contain images? Thanks!

**Comment by pkrush** [comment]
Try cents.tar
Thanks!

**Comment by chmullig** [comment]
Nice, thanks!

**Comment by pkrush** [comment]
OK cents.tar is different set. The .gz fIle is missing.

**Comment by pkrush** [comment]
It will be back up in 15 hours. I really should clean up the old issues in this repo as well. Thanks again. Paul

**Comment by pkrush** [comment]
Now it's back up.
